name: Ubuntu 20.04

on:
  pull_request:
  push:
    branches:    
       - master
    paths-ignore:
       - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y install build-essential cmake curl autoconf automake libtool git libfreetype-dev libssl-dev diffutils pkg-config nasm libfribidi-dev fontconfig
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
