name: FFmpeg on Alpine Linux

on:
  push:

jobs:
  build:
    # Alpine Linux is not natively supported in Github actions, but we can run in a container
    runs-on: ubuntu-latest
    container: alpine:3.7
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --virtual build-dependencies build-base gcc bash cmake curl autoconf automake libtool git freetype-dev openssl-dev diffutils fribidi-dev
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
