name: Ubuntu 20.04

on:
  pull_request:
  push:
    branches:
       - master
    paths-ignore:
       - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y install build-essential cmake curl autoconf automake \
                 libtool git libfreetype-dev fontconfig fontconfig1-dev libssl-dev diffutils pkg-config nasm libfribidi-dev ninja-build \
                 python3 python3-pip python3-setuptools libharfbuzz-dev libharfbuzz-icu0
          pip3 install meson
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
      - name: Verify installation
        run: |
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
