name: MacOS

on:
  pull_request:
  push:
    branches:    
       - master
    paths-ignore:
       - '**.md'

jobs:
  build:
    runs-on: macos-10.15
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install nasm pkg-config curl cmake automake openssl@1.1 fribidi fontconfig
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
