name: ffmpeg
on:
  push:
  pull_request:

jobs:
  ffmpeg:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            CC: gcc
            CXX: g++
          - os: macos-10.15
            CC: clang
            CXX: clang++
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-20.04'
        run: |
             sudo ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
             sudo apt-get update -qq
             sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y install build-essential cmake curl autoconf automake libtool git libfreetype-dev libssl-dev diffutils pkg-config nasm=2.14.02-1
      - name: Install dependencies (mac)
        if: matrix.os == 'macos-10.15'
        run: |
          brew update
          brew install nasm pkg-config curl cmake automake openssl@1.1
      - uses: actions/checkout@v2
      - name: Build ffmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
