name: MacOS

on:
  pull_request:
  push:
    branches:
       - master
    paths-ignore:
       - '**.md'

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install nasm pkg-config automake openssl@1.1 fribidi fontconfig ninja harfbuzz
          # brew install curl cmake
          curl -sL https://bootstrap.pypa.io/get-pip.py | python3
          pip3 install meson
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
      - name: Verify installation
        run: |
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
