name: CentOS

on:
  pull_request:
  push:
    branches:
       - master
    paths-ignore:
       - '**.md'

jobs:
  build:
    # CentOS is not natively supported in Github actions, but we can run in a container
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - name: Install dependencies
        run: |
          yum update -y
          yum -y install curl git autoconf automake cmake gcc gcc-c++ git libtool make pkgconfig \
              zlib-devel openssl-devel patch diffutils fribidi-devel fontconfig-devel freetype-devel \
              python3 python3-pip unzip
          curl -sLo ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip && unzip -o ninja.zip -d /usr/local/bin && rm -f ninja.zip
          pip3 install meson
      - uses: actions/checkout@v2
      - name: Build FFmpeg
        run: |
          bash -x ./ffmpeg-compile/build-ffmpeg.sh
      - name: Verify installation
        run: |
          bash -x ./ffmpeg-compile/test-ffmpeg.sh
